realms:
  # For the conversation service (github.com/shiroyuki/converstaion-service)
  - name: conversation-app
    scopes:
      - name: 'conversation.admin'
      - name: 'conversation.user'
    roles:
      - name: 'conversation.admin'
      - name: 'conversation.user'
    users:
      - name: 'admin'
        password: 'iamgenius!'
        roles: ['conversation.admin']
        email: 'admin@shiroyuki.com'
      - name: 'u_alpha'
        password: 'c5f2376e339de10f' # openssl rand -hex 8
        email: 'u_alpha@conversatio.faux.shiroyuki.com'
        roles: ['conversation.admin']
      - name: 'u_bravo'
        password: '200ab50c5b29302b' # openssl rand -hex 8
        email: 'u_bravo@conversatio.faux.shiroyuki.com'
        roles: ['conversation.user']
    clients:
      - name: 'conversation-app'
        secret: '1a1b7bea5d306f249108c1edb559cd74' # openssl rand -hex 16
        audience: 'http://localhost:8080/'
        grant_types:
          - 'urn:ietf:params:oauth:grant-type:device_code'  # device-code flow
          - 'urn:ietf:params:oauth:grant-type:jwt-bearer'  # on-behalf-of flow
        response_types: ['code']
        scopes:
          # Common Scopes
          - 'openid'
          - 'profile'
          # Flow-specific Scope
          - 'offline_access'  # NOTE: Standard scope
          # Flow-specific Scope
          - 'user.read'  # NOTE: Copied from MS Docs
          # App-specific Scopes
          - 'conversation:admin'
          - 'conversation:user'
    policies:
      - name: 'conversation.admin'
        resource: 'http://localhost:8080/'
        subjects:
          - kind: 'role'
            subject: 'conversation.admin'
        scopes:
          # Common Scopes
          - 'openid'
          - 'profile'
          # Flow-specific Scope
          - 'offline_access'  # NOTE: Standard scope
          # Flow-specific Scope
          - 'user.read'  # NOTE: Copied from MS Docs
          # App-specific Scopes
          - 'conversation:admin'
          - 'conversation:user'
      - name: 'conversation.user'
        resource: 'http://localhost:8080/'
        subjects:
          - kind: 'role'
            subject: 'conversation.user'
        scopes:
          # Common Scopes
          - 'openid'
          - 'profile'
          # Flow-specific Scope
          - 'offline_access'  # NOTE: Standard scope
          # Flow-specific Scope
          - 'user.read'  # NOTE: Copied from MS Docs
          # App-specific Scopes
          - 'conversation:user'
