realms:
  - name: auto-testing
    scopes:
      - name: scope_a
      - name: scope_b
        sensitive: true
      - name: scope_1
    roles:
      - name: role_a
      - name: role_b
    users:
      - name: user_a
        password: alpha
        email: user_a@mini-idp.faux.shiroyuki.com
        roles: [role_a]
      - name: user_b
        password: bravo
        email: user_b@mini-idp.faux.shiroyuki.com
        roles: [role_b]
      - name: user_c
        password: charlie
        email: user_c@mini-idp.faux.shiroyuki.com
    clients:
      - name: 'app_0'
        secret: '1a1b7bea5d306f249108c1edb559cd74' # openssl rand -hex 16
        audience: 'http://localhost:8080/realms/auto-testing-a/'
        grant_types:
          - 'urn:ietf:params:oauth:grant-type:device_code'  # device-code flow
          - 'urn:ietf:params:oauth:grant-type:jwt-bearer'  # on-behalf-of flow
        response_types: ['code']
        scopes:
          # Common Scopes
          - 'openid'
          - 'profile'
          # Flow-specific Scope
          - 'offline_access'  # NOTE: Standard scope
          # Flow-specific Scope
          - 'user.read'  # NOTE: Copied from MS Docs
          # App-specific Scopes
          - 'scope_a'
          - 'scope_b'
      - name: 'app_1'
        secret: '1a1b7bea5d306f249108c1edb559cd74' # openssl rand -hex 16
        audience: 'http://localhost:8080/realms/auto-testing-a/'
        grant_types:
          - 'urn:ietf:params:oauth:grant-type:jwt-bearer'  # on-behalf-of flow
        response_types: ['code']
        scopes:
          # Common Scopes
          - 'openid'
          - 'profile'
          # Flow-specific Scope
          - 'user.read'  # NOTE: Copied from MS Docs
          # App-specific Scopes
          - 'scope_a'
          - 'scope_b'
      - name: 'app_2'
        secret: '1a1b7bea5d306f249108c1edb559cd74' # openssl rand -hex 16
        audience: 'http://localhost:8080/realms/auto-testing-a/'
        grant_types:
          - 'urn:ietf:params:oauth:grant-type:device_code'  # device-code flow
        response_types: ['code']
        scopes:
          # Common Scopes
          - 'openid'
          - 'profile'
          # Flow-specific Scope
          - 'offline_access'  # NOTE: Standard scope
          # App-specific Scopes
          - 'scope_b'
    policies:
      - name: 'iam-policy-for-role-a'
        resource: 'http://localhost:8080/realms/auto-testing-a/'
        subjects:
          - kind: 'role'
            subject: 'role_a'
        scopes:
          # Common Scopes
          - 'openid'
          - 'profile'
          # Flow-specific Scope
          - 'offline_access'  # NOTE: Standard scope
          # Flow-specific Scope
          - 'user.read'  # NOTE: Copied from MS Docs
          # App-specific Scopes
          - 'scope_a'
      - name: 'iam-policy-for-role-b'
        resource: 'http://localhost:8080/realms/auto-testing-a/'
        subjects:
          - kind: 'role'
            subject: 'role_b'
        scopes:
          # Common Scopes
          - 'openid'
          - 'profile'
          # Flow-specific Scope
          - 'offline_access'  # NOTE: Standard scope
          # Flow-specific Scope
          - 'user.read'  # NOTE: Copied from MS Docs
          # App-specific Scopes
          - 'scope_b'